### ISSUE TITLE
Add option to resize canvas without scaling its contents

### ISSUE THREAD

**Issue by Sosasees** [Orama-Interactive/Pixelorama#326] opened 2020-09-05 08:58 UTC
**Pixel-o-rama version:** 0.7

**Feature/enhancement description:**

Literally every other image editor I used before has the option to resize the canvas **without** scaling its contents.
If this option is used instead of scaling,
the content gets cropped if the canvas is ensmalled, or blank space is added if the canvas is embiggened.

This is an example of how the ,,Resize Canvas" menu looks like in every other program:

![grafik](https://user-images.githubusercontent.com/66305550/92301399-e4f0ab80-ef63-11ea-991e-b7bc4bd24023.png)

---

I can't really use Pixel-o-rama right now, because this option to enlarge the canvas later is the backbone of my workflow. I really don't like having a canvas larger than necessary.

For Single-Layer Single-Frame Images, I have this workaround:
1. Cutting the image with [Ctrl] + [C] → [Del] (instead of the usual [Ctrl] + [x] ),
2. then scaling the canvas,
3. then pasting the Cut Contents.

But this is pretty much impossible for Multi-Layer or Multi-Frame images, because I can't Copypaste the contents across windows. And even if I could, the workaround would exponentially increase in time-consuminess the more Layers and Frames are added.

**Comment by OverloadedOrama** [comment] 2020-09-05 10:32
Canvas resizing has already been implemented in v0.8 - duplicate of #268.

**Closed by OverloadedOrama** 2020-09-05 10:32 UTC
Labels: enhancement

**Comment by Sosasees** [comment] 2020-09-05 17:08
I'm sorry about that.
I already looked in the releases tab, but I didn't see version 8.0 in the stable releases (I don't like downloading instable releases).

Additionally, I'm not sure how I missed that duplicate (Most likely I was looking for Canvas Scaling and then forgot to look for Resizing).

Wish you best luck with Pixelorama 8 and 9.

**Comment by OverloadedOrama** [comment] 2020-09-05 17:50
No problem! Pixelorama v0.8 hasn't been released yet (it's currently on its release candidate stage) so it makes sense that people miss some of the new features. If everything goes well, it should be out within the next few weeks. Thank you for the wishes! :D
