### ISSUE TITLE
Error 7 when trying to save files

### ISSUE THREAD

**Issue by DarthMikeSundays** [Orama-Interactive/Pixelorama#465] opened 2021-03-19 15:21 UTC
**Pixelorama version:**
v1.8.2 - stable

**OS/device including version:**
Windows 10 Pro version 2004

**Issue description:**
I was trying to save a file for the first time and I got a file failed to save error 7.

**Comment by Schweini07** [comment] 2021-04-08 18:41
Error 7 stands for a file not being found.

Is this reproducible?
If so could you post the error log?

**Comment by MikeSundaysProgrammer** [comment] 2021-04-09 22:10
Unfortunately, i dont have reproducible steps since it only happens sometimes and I haven't found a correlation between the times it happenned,.but I might be missing something

**Comment by Schweini07** [comment] 2021-04-10 13:05
Can you look at the error logs?

They are located in:
- Windows: `%APPDATA%/Pixelorama/logs`
- Linux: `~/.local/share/godot/app_userdata/Pixelorama/logs`
- Mac: `~/Library/Application Support/Godot/app_userdata/Pixelorama/logs`

Look out for an error that mentions Error 7.

**Comment by DarthMikeSundays** [comment] 2021-09-26 12:05
Sorry for only responding this late, but I must admit I kind of forgot about this issue. Unfortunately, I changed computers and I haven't been using pixelorama lately so I have no logs to show.

**Comment by Schweini07** [comment] 2021-09-26 15:59
Did the error occur on your old machine again after you reported it, or did you already change computer?

**Comment by DarthMikeSundays** [comment] 2021-09-27 19:12
I think it occured again once or twice again in my old machine before I changed to my new one

**Comment by Schweini07** [comment] 2021-09-27 19:43
Do you still have access to your old computer, so you can maybe look at the log files? If not, I think it's fine to close the issue, I not sure we haven gotten any reports like this recently.

**Comment by DarthMikeSundays** [comment] 2021-10-04 16:34
I am sorry, but unfortunately I don't have access to it so I am going to close the issue as you proposed

**Closed** 2021-10-04 16:35 UTC
Labels: bug
