### ISSUE TITLE
Fails to open on ubuntu touch

### ISSUE THREAD

**Issue by Fuseteam** [Orama-Interactive/Pixelorama#740] opened 2022-08-20 15:16 UTC
**Pixelorama version:**
0.10-stable

**OS/device including version:**
Ubuntu Touch OTA-23

**Issue description:**
the app fails to open, not quite sure where to look for logs atm

**Steps to reproduce:**

**Comment by Fuseteam** [comment] 2022-08-21 16:54
i found the logs, i forgot to enable developer mode in Ubuntu Touch earlier (silly me)
here are my logs
[application_click_pixelorama_orama_interactive_pixelorama_0_.log](https://github.com/Orama-Interactive/Pixelorama/files/9389622/application_click_pixelorama_orama_interactive_pixelorama_0_.log)

**Comment by OverloadedOrama** [comment] 2022-08-26 15:31
This looks like a duplicate of #637, so I will close this. Unfortunately, I have no idea why this happens or how to fix it. I'm not familiar with the UT export workflow and it is not supported by Godot out of the box. I will leave the other issue open in case a contributor knows how to fix it, but we may have to give up Ubuntu Touch completely since I do not know how to maintain the platform.

**Closed by OverloadedOrama** 2022-08-26 15:31 UTC
Labels: bug, platform-specific
