### ISSUE TITLE
Deleting a linked cell makes it impossible to link any other cell from that layer

### ISSUE THREAD

**Issue by IagoAndrade** [Orama-Interactive/Pixelorama#218] opened 2020-04-22 21:25 UTC
I was testing the linking cells feature from v0.7, and found this bug.
Steps to reproduce:
Select a cell, enable cell linking, create new frame, delete the frame with the new linked cell, unlink original linked cell, disable cell linking and try to enable it again in any cell from that layer.
Cell linking remains working on cells from other layers. If you enable linking on that layer again and create a new frame, the new cell will contain the last modified version of the originally linked cells, even after deleting all involved frames.

**Comment by OverloadedOrama** [comment] 2020-04-22 21:46
The desired behavior is that if you link cels, draw something and then delete the cels or unlink them, if you link again, the content must be edit, right? I'll see how I can fix it.

**Comment by OverloadedOrama** [comment] 2020-04-22 22:44
I believe the issue was caused because when frames were being deleted, some of their cels which might have been linked, were not removed from linked memory. As such, if you attempted to link new cels after deleting old ones, the content was still saved and was replacing the new linked cels.

I believe I have fixed this, and I'll make a commit very soon, which will close the issue. If after the commit you think that the issue is still happening, feel free to re open it!

**Closed** 2020-04-22 22:46 UTC
Labels: bug
