### ISSUE TITLE
Option to change icon pack or have more colorful icons.

### ISSUE THREAD

**Issue by yuyutsupoudel** [Orama-Interactive/Pixelorama#310] opened 2020-08-16 13:53 UTC
There should be a option to change icon pack also.
What i think is we should have dark and light icon pack as base pack and option to apply a new icon pack. If new icon pack is missing some icons, it should apply icons from base pack.
Even if its hard to implement icon change feature, i think having more color full icons as a option to change would help gaining new users. Icons Something like below would help a lot.
[Example](https://i.postimg.cc/mZQ04j6f/5.png)

**Comment by luiq54** [comment] 2020-08-16 14:03
Duplicate of #287

**Closed** 2020-08-16 14:04 UTC
Labels: enhancement
