### ISSUE TITLE
Adding a Tilemap system

### ISSUE THREAD

**Issue by WaterExpensive** [Orama-Interactive/Pixelorama#714] opened 2022-07-06 19:44 UTC
**Introduction**
Hello!
I've been using Pixelorama for as long as I can remember, seeing it as a better and open-source to Pyxel-edit and Aseprite. However, what's been missing for my use is a Tilemap system.

**Tilemap system?**

A Tilemap system makes it easy to create tiles and check whether the created tiles fit each other for use in gamedev and normal art.
![image](https://user-images.githubusercontent.com/34092413/177631237-f4d75727-40a4-47a2-b449-772d97661f70.png)

**How would a Tilemap system help?**

As mentioned above, it facilitates the process of creating Tilemaps by trial and error, whereby similarities in the tiles can be fixed before putting it for use in the engine.

![image](https://user-images.githubusercontent.com/34092413/177631668-fe54cfd5-8ff8-438d-ac9d-27284b39bf34.png)
_not important, just a quick tree made in Pixelorama._

**Comment by OverloadedOrama** [comment] 2022-07-06 21:55
Hello, thank you for the proposal! This is a duplicate of #611, so I will close this issue and feel free to continue the discussion there! :)

PS: We only use Issues for bug reports. Please open [Discussions](https://github.com/Orama-Interactive/Pixelorama/discussions) for feature proposals instead.

**Closed by OverloadedOrama** 2022-07-06 21:55 UTC
