### ISSUE TITLE
Shortcut for adjusting brush size

### ISSUE THREAD

**Issue by pistachio-diffuser** [Orama-Interactive/Pixelorama#777] opened 2022-11-08 17:21 UTC
Please, add a keyboard shortcut for adjusting a brush size like in aseprite, blender or other programs. I want to speed up my workflow in Pixelorama. I would love to see this feature. It will improve my experience of using this already wonderful program :)

**Comment by OverloadedOrama** [comment] 2022-11-08 18:05
Duplicate of #776.

**Closed by OverloadedOrama** 2022-11-08 18:05 UTC
