### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by niceloaf** [Orama-Interactive/Pixelorama#325] opened 2020-09-01 03:14 UTC
It would be nice to have tabs so users can multitask in creating and editing images without having to open another project tediously.

**Comment by Schweini07** [comment] 2020-09-01 10:50
Tabs are already added in 0.8!
You can test them in your browser here: https://orama-interactive.github.io/Pixelorama/early_access/

**Comment by OverloadedOrama** [comment] 2020-09-01 10:51
Duplicate of #298.

**Closed by OverloadedOrama** 2020-09-01 10:51 UTC
Labels: enhancement
