### ISSUE TITLE
Frame change shortcuts using Ctrl do not work on Mac

### ISSUE THREAD

**Issue by gingerbeardman** [Orama-Interactive/Pixelorama#273] opened 2020-06-25 19:12 UTC
The following _do not_ work:

- Ctrl+Home
- Ctrl+Left
- Ctrl+Right
- Ctrl+End

> I have also tried Alt and Cmd, instead of Ctrl, just in case. But the above shortcuts do not work.

The following work OK:

- F4
- F5

The following tool selection also work OK:

- U
- Alt+U
- (and all other other tools)

Other shortcuts using Control work OK:

- New/Save/Export
- Show Rulers
- (all other menu items)

**Comment by wyattbiker** [comment] 2020-06-25 20:23
Just curious what are the 
```
Ctrl+Home
Ctrl+Left
Ctrl+Right
Ctrl+End
```
supposed to do?

**Comment by gingerbeardman** [comment] 2020-06-25 21:31
As in the issue subject: frame change

![Screen shot 2020-06-25 at 22 30 58](https://user-images.githubusercontent.com/49612/85797450-8d4bed80-b733-11ea-8925-954fdfbd6b59.png)

**Comment by Schweini07** [comment] 2020-06-26 11:37
Does something else happen when you press press Ctrl+Left or Ctrl+Right? As it could be that Godot is grabbing focus on an other UI element.

**Comment by OverloadedOrama** [comment] 2020-06-26 12:04
This seems like a duplicate of #67. Do Command + Ctrl work? If they do, we should close the issue and continue on #67.

**Comment by gingerbeardman** [comment] 2020-06-26 12:20
@Schweini07 nothing happens when I press Ctrl+Left/Right/Home/End

@OverloadedOrama as mentioned above menus that use Control+Command work OK (like File > New/Save/Export)

Also, why do some shortcuts say Ctrl and others say Control? Any bearing on this issue?

If you think this isa dupe of 67, feel free too close. You know the app better than me.

**Comment by silocoder** [comment] 2020-06-26 15:31
Ok for the Macbook  it seems to work as follows:
Fn=Function key.

Ctrl+Home (jump to first frame) -> Fn+Ctrl+Cmd+Right
Ctrl+Left (goto previous frame) Ctrl+Cmd+Right
Ctrl+Right (goto next frame)  Ctrl+Cmd+Left
Ctrl+End (jump to last frame) Fn+Ctrl+Cmd+Left

The Macbooks have no Home/End key. Normally it is Fn+Right/Left.

So yes you can add this to issue #67

**Comment by gingerbeardman** [comment] 2020-06-26 15:35
FWIW I am using a full size keyboard with Home/End and numeric pad.

**Comment by OverloadedOrama** [comment] 2020-07-01 00:14
I'll close this as a duplicate of #67 then. Feel free to continue the discussion there, and I'll comment there too if I find a way to deal with the issue.

**Closed by OverloadedOrama** 2020-07-01 00:14 UTC
Labels: bug, platform-specific
