### ISSUE TITLE
Canvas locks after Alt + Tab to another window

### ISSUE THREAD

**Issue by maxvone** [Orama-Interactive/Pixelorama#601] opened 2021-11-25 17:13 UTC
**Pixelorama version:**
0.9

**OS/device including version:**
Windows 10

**Issue description:**
When minimizing Pixelorama using "Alt + Tab" combination and then opening it using "Alt + Tab" again canvas locks and you lose the ability to draw until pick an instrument.

**Steps to reproduce:**
1. Open Pixelorama program
2. Pick pencil instrument
2. Alt + Tab to another window
3. Press "Alt + Tab" once again to open Pixelorama
4. Try to draw

**Comment by OverloadedOrama** [comment] 2021-11-25 17:17
Duplicate of #552. This bug has already been fixed and the fix will be included in the next version. Thank you for reporting!

**Closed by OverloadedOrama** 2021-11-25 17:17 UTC
Labels: bug
