### ISSUE TITLE
CMD/CTRL hotkeys 

### ISSUE THREAD

**Issue by KripC2160** [Orama-Interactive/Pixelorama#351] opened 2020-10-13 08:43 UTC
I wish the program had cmd/ctrl z and cmd/ctrl shift z to undo and redo since having these universal hotkeys makes the workflow much smoother

**Comment by OverloadedOrama** [comment] 2020-10-13 11:20
Ctrl-Z is already used for undo, and Ctrl-Shift-Z (and Ctrl-Y) for redo. If you're talking about macOS, then this is a duplicate of #67.

**Closed by OverloadedOrama** 2020-10-13 11:20 UTC
Labels: enhancement
