### ISSUE TITLE
Moving outside canvas with rectangle selection crops the image.

### ISSUE THREAD

**Issue by azagaya** [Orama-Interactive/Pixelorama#38] opened 2019-12-14 22:00 UTC
Hi,
Selecting some part of a drawing and moving it outside canvas, crops the image.
Other pixel art tools don't show this behaviour, so i think it would be nice not to cropping the image when outside canvas. 
Perhaps the image itself should be bigger (or grow) and the viewport of the selected resolution. 

If this is wanted, and i get some guidelines of where to look, i could give this change a try.

**Comment by OverloadedOrama** [comment] 2019-12-15 12:23
Hello! I didn't reply here because we were talking on Discord about this, but I'll reply here too in case anyone else wants to give it a try too. The code of the rectangle selection is scattered in 2 places, Canvas.gd under _process() and in SelectionRectangle.gd. SelectionRectangle.gd is where the problem can be fixed, most likely.

The problem is that if you take a selection and move it outside the canvas and then drag it back, all pixels would be black. So to combat this, I made the pixels invisible instead. I'll try to give it a shot in solving this some time in the future, but feel free to contribute as well!

**Comment by novhack** [comment] 2021-12-06 09:33
I would consider this issues resolved.
In pre-0.9 versions every selection move was immediately committed - this behaviour is described in this issue.
Since v0.9 a selected pixels can be freely moved around until the movement is committed by the user by deselecting or Enter is pressed.

**Closed** 2021-12-06 19:59 UTC
Labels: change
