### ISSUE TITLE
It doesn't work on mac:(((

### ISSUE THREAD

**Issue by 0Fruto** [Orama-Interactive/Pixelorama#240] opened 2020-05-21 15:30 UTC
# It doesn't work on mac and IDK why
Look, I love your product and I wanna use it __soooo badly__! However, I actually **can't**:(
You can see a screenshot of error below, if it's my fault, please, just tell me what I have to doooo!!
<img width="519" alt="image" src="https://user-images.githubusercontent.com/35031001/82575054-a095f700-9b90-11ea-9b8f-cd1ef4f8934a.png">
I also tried to build it on my own, __but it just closes after a few seconds:((__
Also, if I can help you by providing any useful information, feel free to ask;)

**Comment by OverloadedOrama** [comment] 2020-05-21 15:32
Have you tried following these instructions?

"You may encounter some errors saying that Pixelorama is damaged. This is because the latest versions of MacOS mark the launcher of unknown binaries as a non-executable file. This most likely has to do with the fact that Pixelorama is not signed. 

After you extract the .zip file, right-click on the .app file >choose Open in the dropdown then click Open in the warning dialog. Alternatively, you can right click the .app > show package contents, then open a terminal inside its Contents/MacOS folder. Then, type chmod +x Pixelorama . Go back to the .app file and you can now open it normally. "

**Comment by 0Fruto** [comment] 2020-05-21 15:44
<img width="464" alt="image" src="https://user-images.githubusercontent.com/35031001/82576976-04212400-9b93-11ea-9217-898ef457b5bc.png">

👆that is what happening when i press open in dropdown

**Comment by 0Fruto** [comment] 2020-05-21 17:21
Wow, I managed launching this app, thank you for help!!!<3

**Comment by OverloadedOrama** [comment] 2020-05-21 17:43
Awesome! I'll go ahead and close this issue then! Sorry for the trouble caused, I don't own a Mac and it's hard to test if it works properly. The issue is most likely being caused because Pixelorama is not signed, and therefore not trusted by macOS. Signing it seems like a difficult process, and also costs money, so I doubt it will happen soon. For now, Mac users will have to follow the workaround method I posted above to get Pixelorama working.

**Closed by OverloadedOrama** 2020-05-21 17:43 UTC
Labels: platform-specific
