### ISSUE TITLE
app not opening from store download on ubuntu 22.04

### ISSUE THREAD

**Issue by a-krum-of-bread** [Orama-Interactive/Pixelorama#1071] opened 2024-08-09 22:02 UTC
Pixelorama version: 1.0.1
os
ubuntu  22.04

I was unable to open the app after an update to the app and after deleting and reinstalling it still will not open at all nor would it open when reinstalling from the terminal.
then I later opened the file directory to find that there were missing files that were supposed to be referred 
I am not sure if this is an issue with the store or the app

**Comment by Variable-ind** [comment] 2024-08-09 22:05
Hy, there was a similar issue on GitHub
> Good tool! Although after the update to Ubuntu 20 it stopped working. But I have already solved this issue. And so thanks for the tool.

Here's how he solved it:

> I removed the Pixelorama program installed via snap because the new version requires the GLIBC_2.28 library, which I don’t have. The error looked like this: /snap/pixelorama/199/Pixelorama.x86_64: /lib/x86_64-linux-gnu/libc.so.6: version ‘GLIBC_2.28’ not found (required by /snap/pixelorama/199/Pixelorama.x86_64) After removing the snap version, I went to itch.io, downloaded Pixelorama from your page, extracted the archive, and ran it through the terminal using the command ./Pixelorama.x86. Everything works, and I am using the program now.

**Comment by OverloadedOrama** [comment] 2024-08-09 23:05
Duplicate of #1062

**Closed by OverloadedOrama** 2024-08-09 23:05 UTC
Labels: bug
