### ISSUE TITLE
Setting Tool Shortcut To Use Control Doesn't Work

### ISSUE THREAD

**Issue by 123outerme** [Orama-Interactive/Pixelorama#935] opened 2023-11-05 15:20 UTC
**Pixelorama version:**
v0.11.3-1, installed from the AUR package "pixelorama-bin".
(I know there are visual issues with another AUR package for Pixelorama, but this one doesn't have those issues)

**OS/device including version:**
EndeavourOS Arch Linux (up to date)

**Issue description:**
After changing a tool shortcut to use a Control+\<Key> keybind, using the keybind does not select the tool.

**Steps to reproduce:**
1. Change a tool shortcut to Control+\<Key> for any additional key (I was testing with Control+W).
2. Exit the shortcuts menu and press the keys for the shortcut. The tool should not be selected.

**Comment by OverloadedOrama** [comment] 2023-11-06 00:49
The issue should be fixed now in commit [5b67880](https://github.com/Orama-Interactive/Pixelorama/commit/5b67880a9bddbf0446fa37eb3f7bdfbce45124ec) for 1.x and [7c0de64](https://github.com/Orama-Interactive/Pixelorama/commit/7c0de64b920e8846085b4775fb53650b7c9d82be) for 0.11.4. 

Originally this was because of issue #406. The solution we used back then meant that users couldn't use <kbd>Control</kbd> in their shortcuts for the tools. The fix I committed just now does not seem to reproduce that issue.

Thanks for reporting!

**Closed by OverloadedOrama** 2023-11-06 00:49 UTC
Labels: bug
