### ISSUE TITLE
Pixelorama install is damaged

### ISSUE THREAD

**Issue by haz-ai** [Orama-Interactive/Pixelorama#537] opened 2021-09-19 11:42 UTC
**Pixelorama version:**
V 0.9

**OS/device including version:**
macOS Big Sur 11.5.2 (20G95)

**Issue description:**
Pixelorama install shows as a damaged app when trying to install on MacOS.

**Steps to reproduce:**
Download and try to run on MacOS

**Comment by OverloadedOrama** [comment] 2021-09-19 12:23
This is most likely a duplicate of #516, please refer to my response there. Disabling Gatekeeper should fix the problem. https://disable-gatekeeper.github.io/

If it doesn't work, feel free to re-open the issue.

**Closed by OverloadedOrama** 2021-09-19 12:23 UTC
Labels: bug
